name: nepali_kit_example
description: Demonstrates how to use the nepali_kit package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.3.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  nepali_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
